apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: ticketing-microservice
build:
  local:
    push: true
  insecureRegistries:
  - registry.local
  artifacts:
    - image: registry.local/ticketing-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
deploy:
  kubectl:
    defaultNamespace: ticketing-microservice
manifests:
  rawYaml:
    - infrastructure/k8s/*
    